### ISSUE TITLE
CheckList Aprobar Sprint 2

### ISSUE THREAD

**Issue by Minuke** [ISPPNightTurn/Clubby#177]
Checklist a revisar antes de la entrega prevista para el dia 31/03/2020 (es recomendable hacerlo un dia antes por si faltan cosas de ultima hora):

Tareas a revisar 

- [ ] **Medir las mejoras #163** 
- [ ] **Planificacion pilotaje #164**
- [ ] **Grafica sonarcloud #165**
- [ ] **Metrica Medicion equipo #166**
- [ ] **Retrospectiva (lecciones aprendidas) #167**
- [ ] **Tests #168**
- [ ] **Mejoras en la interfaz #169**
- [ ] **Mejoras Software Sprint 1 #170**
- [ ] **Nueva demo con nueva interfaz #171**
- [ ] **Anuncio #172**
- [ ] **Gestion del codigo #173**

Se deben considerar tambien los siguientes elementos:

- [ ] **Feedback recibido de los clientes y que haremos en funcion del feedback recibido**
- [ ] **Todas las graficas tienen que tener una leyenda**
- [ ] **Explicar mejor la diapositiva de las metricas de medicion del equipo (no poner diagrama ni tabla si no se lee bien, sino vas a explicar algo no se pone)**
- [ ] **Explicar porque un miembro no ha rendido del todo bien (si hay alguno que tenga muy baja nota)**
- [ ] **Incluir un elevator pitch (no hace falta ponerlo por escrito)**
- [ ] **Los objetivos de las soluciones faltan (diap 19)**
- [ ] **No es recomendable incluir elementos del backlog de futuros sprints (APIs), sino incluir pruebas**
- [ ] **Despliegue en una url diferente para el sprint 2**
- [ ] **Una vez que todo este chequeado, volver a revisar el documento de feedback por si faltase alguna que otra cosa**
