### ISSUE TITLE
Pensar en mas inicios efectivos

### ISSUE THREAD

**Issue by Minuke** [ISPPNightTurn/Clubby#84]
Investigar sobre más inicios efectivos. Hay que hacer un inicio diferente cada semana para mantener la atención del público.

Lo ideal es pensar en un buen inicio efectivo para cada entrega evaluable, ya que si hacemos un inicio efectivo en días no evaluables y queremos repetirlo puede perder efecto. Para los días no evaluables podemos improvisar y si sale bien, mejorarlo y hacerlo en un día evaluable. Así que como mínimo, hay que pensar en 5 inicios efectivos. Cada vez que consideremos que tenemos pensado un buen inicio efectivo, se marcara en la siguiente checklist, cerrando la tarea cuando se complete dicha checklist:

 - [x] : Primer Inicio Efectivo 
 - [ ] : Segundo Inicio Efectivo
 - [ ] : Tercer Inicio Efectivo
 - [ ] : Cuarto Inicio Efectivo
 - [x] : Quinto Inicio Efectivo

**Comment by Pablo17p** [comment]
El inicio efectivo del 18 de marzo está ya más o menos planteado, pero es conveniente que se formalicen más ideas para próximas ideas.

**Comment by Minuke** [comment]
Se ha pensado también en un inicio efectivo de cara a la ultima entrega, que requerirá la participación de todos y un poco de ensayo.
